import type { Metadata } from 'next'
import AdminB2CLayoutWrapper from '@/components/b2c-admin/common-component/AdminB2CLayoutWrapper'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<div className="font-main overflow-x-hidden">
			<AdminB2CLayoutWrapper>{children}</AdminB2CLayoutWrapper>
		</div>
	)
}
