import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import { ADLaM_Display } from 'next/font/google'

const adlam = ADLaM_Display({
	subsets: ['latin'],
	weight: ['400'],
	variable: '--font-adlam',
})

const poppinsFont = Poppins({
	style: 'normal',
	subsets: ['latin'],
	weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
	variable: '--font-poppins',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en" className={(poppinsFont.variable, adlam.variable)}>
			<body className="font-main overflow-x-hidden">{children}</body>
		</html>
	)
}
