import type { Metadata } from 'next'
import MaxWidthWrapper from '@/components/admin/max-width-wrapper'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<div className="font-main overflow-x-hidden">
			<MaxWidthWrapper>{children}</MaxWidthWrapper>
		</div>
	)
}