import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import '../globals.css'
import { ADLaM_Display } from 'next/font/google'
import Header from '@/components/layout/Header'
import Footer from '@/components/layout/Footer'
// import MaxWidthWrapper from '@/components/max-width-wrapper'

const adlam = ADLaM_Display({
    subsets: ['latin'],
    weight: ['400'],
    variable: '--font-adlam',
})

const poppinsFont = Poppins({
    style: 'normal',
    subsets: ['latin'],
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
    variable: '--font-poppins',
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
     const headerUser = {
    name: "Educator Name",
    role: "Teacher",
    avatarSrc: "/teacher-b2b/profile.png",
  };
    return (
        <html lang="en" className={(poppinsFont.variable, adlam.variable)}>
            <body className="font-main overflow-x-hidden">
                <Header user={headerUser} />
                {/* <MaxWidthWrapper> */}
                    <div className="bg-gray-100">
                {children}
                    </div>
                {/* </MaxWidthWrapper> */}
                <Footer />
                </body>
        </html>
    )
}
