import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import '@/app/globals.css'
import { ADLaM_Display } from 'next/font/google'
import Footer from '@/components/layout/Footer'
// import MaxWidthWrapper from '@/components/max-width-wrapper'

const adlam = ADLaM_Display({
    subsets: ['latin'],
    weight: ['400'],
    variable: '--font-adlam',
})

const poppinsFont = Poppins({
    style: 'normal',
    subsets: ['latin'],
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
    variable: '--font-poppins',
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
  
    return (
        <div lang="en" className={`${poppinsFont.variable} ${adlam.variable}`}>
            <div className="font-main">
                <div className="bg-gray-100">{children}</div>
            </div>
        </div>
    );
}